= L'epreuve du feu - coding accelerator
Doc Writer <https://art-dambrine.ovh/asciidoc[asciidoc @art-dambrine]>
:toc: left
:hide-uri-scheme:
:source-highlighter: highlight.js

== Consignes

- avec le langage que vous souhaitez

- exécuter votre programme depuis le shell

== L'escalier

Créer un script qui affiche un escalier en fonction du premier argument.

Ex. d’appel du script :
--------
$> ./escalier 4
#
##
###
####
--------

== Majuscule

Créer un script qui affiche une lettre sur deux en majuscule et le reste en minuscule de la
chaîne de caractères du premier argument.

Ex. d’appel du script :
----------
$> ./majuscule “Bien le bonjour!”
bIeN lE bOnJoUr!
----------


== Factoriel en récursif

Créer un script qui calcul la factoriel du nombre passé en argument.

Ex. d’appel du script :
---------
$> ./factoriel 3
6
---------


== Tri

Créer un script qui affiche les valeurs qui lui sont passées en argument triées par ordre
décroissant.

Bonus : implémenter plusieurs algorithme de tri (tri à bulle, tri sélectif, ... )
Ex. d’appel du script :
---------
$> ./tri 4 5 1 3 2
5 4 3 2 1
---------


== Rectangle
Créer un script qui affiche la position du carré passé en premier argument dans le carré du
second argument.

Ex. d’appel du script :
--------
$> ./rectangle c1.txt c2.txt
2,1

$> cat c1.txt
123
321
123

$> cat c2.txt
930870
081235
973217
091230
883700
--------


== Anagrammes

Créer un script qui affiche tous les anagrammes du premier argument contenu dans le
fichier du second arguments.

Ex. d’appel du script :
---------
$> ./anagramme arbre fr.txt
[“arbre”, “barre”]
$> cat fr.txt
amour
arbre
balade
barre
beau
---------